### ISSUE TITLE
[IMPROVEMENT] Support method descriptor callbacks

### ISSUE THREAD

**Issue by d00astro** [lyngon/redgrease#95]
**Which part of RedGrease does it concern?**
(Indicate all that apply)
- [x] client library functionality
- [x] runtime / server library functionality
- [ ] cli
- [ ] docker image
- [ ] tests
- [ ] documentation
- [ ] other

**Is your feature request related to a problem? Please describe.**
Currently this is not possible to pass a 'method descriptor' (e.g. `str.split` ) as a callbacks, 

```python
redgrease.KeysReader().values().flatmap(str.split).countby().run()
```
It raises the error:
ResponseError(['Traceback (most recent call last):\n', '  File "<string>", line 1, in <module>\n', '  File "<string>", line 169, in deco\n', 'spam.error: flatmap argument must be a function\n'])

The work-around is to wrap in a lambda:
```python
KeysReader().values().flatmap(lambda x: x.split()).countby().run()
```
This is annoying and unintuitive. 

**Describe the solution you'd like**
Don't have a clear solution in mind, but maybe some workaround  can be baked into RedGrease somehow.
Maybe using `dill` instead of `cloudpickle` solves this automatically? 
Maybe the `Operation` can do a check if the callback is of type `method_descriptor`, and if so wrap it in a lambda automagically? 👈🏻 (should be relatively easy, no?)

**Describe alternatives you've considered**
Maybe RedisGears code needs to be poked at?
The error arise in "redisgears_python.c" during the various checks:
```c
if(!PyObject_TypeCheck(extractor, &PyFunction_Type)){
        PyErr_SetString(GearsError, "groupby extractor argument must be a function");
        return NULL;
    }
```

**Additional context**
No

**Comment by d00astro** [comment]
Spanner:
```python

def wrap(op):
    def wrapped_op(x):
       return  op(x)
   return wrapped_op

if op.__class__.__name__..startswith("method"):
   op = wrapped(op)
```
